name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test container
        run: |
          docker compose build
          docker compose run --rm web pytest
      - name: Run Bandit security scan
        run: |
          pip install bandit

          bandit -r . -q -ll --exclude ./tests --exit.zero || {
            echo "Bandit found  potential security issues."
            echo "Scanning for medium and high severity issues that should fail the pipeline."
            bandit -r . --exclude ./tests --level medium --confidence medium --format custom --output ./.bandit_report.json
            if [ -s ./.bandit_report.json ]
            then
              cat ./.bandit_report.json
              exit 1
            fi
          }
      -name: Run OWASP Dependency Check
